### ISSUE TITLE
airdrop is not available

### ISSUE THREAD

**Issue by zeishuai** [SaileshAndra/Dell-Inspiron-3668-hackintosh_BigSur#1]
Thanks for your files, it works good on my Dell 3668 so far.
there are three problems with it, the HDMI graphic(I have fixed it by the method from the internet), HDMI audio (I have used USB audio instead), the last one is airdrop( wifi&bluetooth), which does not work at all. I really don't know how to fix it. kindly let us know if you have any idea.

**Comment by SaileshAndra** [comment]
It is good that it is working for you, and well to make the wifi and Bluetooth work, you have to replace the factory wifi card with a 3rd party wifi card, that can work out of the box. The one that this device has is not supported so I had to change mine.

**Comment by zeishuai** [comment]
Thanks for your explanation, will have a try.
Have a good day!😜😜
